Programação Web/TrabalhoFinalRentCar/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrabalhoFinalRentCar.Data;
using TrabalhoFinalRentCar.Models;

namespace TrabalhoFinalRentCar.Controllers
{
    public class ReviewsController : Controller
    {

    }
}

Programação Web/TrabalhoFinalRentCar/Controllers/VeiculosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TrabalhoFinalRentCar.Data;
using TrabalhoFinalRentCar.Models;

namespace TrabalhoFinalRentCar.Controllers
{
    namespace RentACar.Controllers
    {
        public class VeiculosController : Controller
        {
            private readonly ApplicationDbContext _context;

            public VeiculosController(ApplicationDbContext context)
            {
                _context = context;
            }

            // GET: Veiculos
            public async Task<IActionResult> Index(int? preco)
            {
               ViewData["ListaDeVeiculos"] = new SelectList(_context.Veiculo.ToList());
                ViewData["ListaDeEmpresas"] = new SelectList(_context.Empresas.ToList());
                ViewData["ListaDeReview"] = new SelectList(_context.Reviews.ToList());
                ViewData["EmpresaId"] = new SelectList(_context.Empresas, "Id", "Nome");
             
                if (preco == 1)
                {
                    return View(await _context.Veiculo.OrderBy(c => c.Custo).ToListAsync());
                }

                if (preco == 2)
                {

                    return View(await _context.Veiculo.OrderByDescending(c => c.Custo).ToListAsync());
                }

                if (preco == 3)
                {

                    return View(await _context.Veiculo.OrderBy(c => c.EmpresaAssociada.Review).ToListAsync());
                }


                return View(await _context.Veiculo.ToListAsync());
            }



            [HttpPost]
            public async Task<IActionResult> Index(String TextoAPesquisar, DateTime DataLevantamento, DateTime DataEntrega)
            {
                ViewData["Title"] = "Lista de Veiculos com '" + DataLevantamento + DataEntrega + "'";
                ViewData["ListaDeVeiculos"] = new SelectList(_context.Veiculo.ToList());
                ViewData["ListaDeEmpresas"] = new SelectList(_context.Empresas.ToList());
                ViewData["ListaDeReview"] = new SelectList(_context.Reviews.ToList());
                ViewData["EmpresaId"] = new SelectList(_context.Empresas, "Id", "Nome");


                if (TextoAPesquisar != null)
                {
                    return View(await _context.Veiculo.Where(c => c.Localizacao.Equals(TextoAPesquisar) || c.Tipo.Equals(TextoAPesquisar)).ToListAsync());
                }


                if (DataLevantamento != null)
                {
                    return View(await _context.Veiculo.Where(c => c.DataLevantamento.Equals(DataLevantamento)).ToListAsync());
                }

                if (DataEntrega != null)
                {
                    return View(await _context.Veiculo.Where(c => c.DataEntrega.Equals(DataEntrega)).ToListAsync());
                }



                return null;

            }


            public async Task<IActionResult> IndexFuncionario(int? preco)
            {
                ViewData["ListaDeVeiculos"] = new SelectList(_context.Veiculo.ToList());
                ViewData["ListaDeEmpresas"] = new SelectList(_context.Empresas.ToList());
                ViewData["ListaDeReview"] = new SelectList(_context.Reviews.ToList());
                ViewData["EmpresaId"] = new SelectList(_context.Empresas, "Id", "Nome");

                if (preco == 1)
                {
                    return View(await _context.Veiculo.OrderBy(c => c.Custo).ToListAsync());
                }

                if (preco == 2)
                {

                    return View(await _context.Veiculo.OrderByDescending(c => c.Custo).ToListAsync());
                }

                if (preco == 3)
                {

                    return View(await _context.Veiculo.OrderBy(c => c.EmpresaAssociada.Review).ToListAsync());
                }


                return View(await _context.Veiculo.ToListAsync());
            }




            // GET: Veiculos/Details/5
            public async Task<IActionResult> Details(int? id)
            {
                if (id == null || _context.Veiculo == null)
                {
                    return NotFound();
                }

                var veiculo = await _context.Veiculo
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (veiculo == null)
                {
                    return NotFound();
                }

                return View(veiculo);
            }

            // GET: Veiculos/Create
            public IActionResult Create()
            {
                return View();
            }

            // POST: Veiculos/Create
            // To protect from overposting attacks, enable the specific properties you want to bind to.
            // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Create([Bind("Id,Marca,Matricula,Tipo,Localizacao,DataLevantamento,DataEntrega,Custo")] Veiculo veiculo)
            {
                if (ModelState.IsValid)
                {
                    _context.Add(veiculo);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                return View(veiculo);
            }

            // GET: Veiculos/Edit/5
            public async Task<IActionResult> Edit(int? id)
            {
                if (id == null || _context.Veiculo == null)
                {
                    return NotFound();
                }

                var veiculo = await _context.Veiculo.FindAsync(id);
                if (veiculo == null)
                {
                    return NotFound();
                }
                return View(veiculo);
            }

            // POST: Veiculos/Edit/5
            // To protect from overposting attacks, enable the specific properties you want to bind to.
            // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
            [HttpPost]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> Edit(int id, [Bind("Id,Marca,Matricula,Tipo,Localizacao,DataLevantamento,DataEntrega,Custo")] Veiculo veiculo)
            {
                if (id != veiculo.Id)
                {
                    return NotFound();
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        _context.Update(veiculo);
                        await _context.SaveChangesAsync();
                    }
                    catch (DbUpdateConcurrencyException)
                    {
                        if (!VeiculoExists(veiculo.Id))
                        {
                            return NotFound();
                        }
                        else
                        {
                            throw;
                        }
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(veiculo);
            }

            // GET: Veiculos/Delete/5
            public async Task<IActionResult> Delete(int? id)
            {
                if (id == null || _context.Veiculo == null)
                {
                    return NotFound();
                }

                var veiculo = await _context.Veiculo
                    .FirstOrDefaultAsync(m => m.Id == id);
                if (veiculo == null)
                {
                    return NotFound();
                }

                return View(veiculo);
            }

            // POST: Veiculos/Delete/5
            [HttpPost, ActionName("Delete")]
            [ValidateAntiForgeryToken]
            public async Task<IActionResult> DeleteConfirmed(int id)
            {
                if (_context.Veiculo == null)
                {
                    return Problem("Entity set 'ApplicationDbContext.Veiculo'  is null.");
                }
                var veiculo = await _context.Veiculo.FindAsync(id);
                if (veiculo != null)
                {
                    _context.Veiculo.Remove(veiculo);
                }

                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            private bool VeiculoExists(int id)
            {
                return _context.Veiculo.Any(e => e.Id == id);
            }
        }
    }

}

Programação Web/TrabalhoFinalRentCar/Views/Shared/FuncionarioPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using TrabalhoFinalRentCar.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


@if (User.Identity.IsAuthenticated && User.IsInRole("Funcionario"))
{
        <a class="#" style="color: #FFFFFF;font-size: 14px;text-decoration: none;font-family:'Playfair Display';margin-left: 15px; margin-right: 15px;display:inline-block;" asp-area="" asp-controller="Reservations" asp-action="ListReservations">Reservations</a>


}

Programação Web/TrabalhoFinalRentCar/Views/Shared/_AdminPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using TrabalhoFinalRentCar.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


@if (User.Identity.IsAuthenticated && User.IsInRole("Administrator"))
{


    <a class="#" style="color: #FFFFFF;font-size: 14px;font-family:'Playfair Display';margin-left: 15px; margin-right: 15px;" asp-area="" asp-controller="User" asp-action="Clients">Clients</a>
    <a class="#" style="color: #FFFFFF;font-size: 14px;font-family:'Playfair Display';margin-left: 15px"asp-area="" asp-controller="User" asp-action="Owners">Owners</a>
    
    
}

Programação Web/TrabalhoFinalRentCar/Views/Shared/_ClientPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using TrabalhoFinalRentCar.Models
@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


@if (User.Identity.IsAuthenticated && User.IsInRole("Client"))
{
    <a class="#" style="color: #FFFFFF;font-size: 14px;text-decoration: none;font-family:'Playfair Display';margin-left: 15px; margin-right: 15px;display:inline-block;" asp-area="" asp-controller="Reservations" asp-action="Index">Reservation History</a>
    <a class="#" style="text-decoration: none;font-family:'Playfair Display';margin-left: 15px; margin-right: 15px;display:inline-block;"asp-area="" asp-controller="Reviews" asp-action="ClientHistory">Reviews</a>

}

Programação Web/TrabalhoFinalRentCar/Views/Shared/_Layout.cshtml
<style type="text/css">
    html, body {
        height: 100%;
        width: 100%;
    }

    .auth {
        float: right;
        display: inline-block;
    }

    .topnav {
        float: left;
    }

    .navMenu {
        overflow: hidden;
        padding: 10px;
        height: 50px;
        background: rgb(33,33,39);
        background: linear-gradient(90deg, rgba(33,33,39,1) 0%, rgba(33,33,39,1) 100%, rgba(33,33,39,1) 100%);
    }


        .navMenu a {
            color: #f6f4e6;
            font-size: 14px;
            text-decoration: none;
            text-transform: uppercase;
            font-family: 'Playfair Display';
            margin-left: 15px;
            margin-right: 15px;
        }


    nav a,
    nav a:after,
    nav a:before {
        transition: all .5s;
    }


    nav a {
        position: relative;
    }

        nav a:after {
            position: absolute;
            bottom: 0;
            left: 0;
            right: 0;
            margin: auto;
            width: 0%;
            content: '.';
            color: transparent;
            background: #aaa;
            height: 1px;
        }

        nav a:hover:after {
            width: 100%;
        }

</style>


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rental4You</title>
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet" />
    <link href='https://fonts.googleapis.com/css?family=Playfair Display' rel='stylesheet'>
    <link rel="shortcut icon" href='@Url.Content("~/logo.ico")'>
    <link rel="stylesheet" href="~/css/style.css" />
    <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.6.0/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/jq-3.6.0/dt-1.11.3/b-2.1.1/sc-2.0.5/sb-1.3.0/sp-1.4.0/sl-1.3.4/datatables.min.css" />
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" />
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

</head>
<body>
    <nav class="navMenu">
        <div class="topnav">
            <a class="#" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
            <a class="#" asp-area="" asp-controller="Veiculos" asp-action="Index">Catálogo</a>
            <partial name="_FuncionarioPartial.cshtml" />

        </div>
        <div class="auth">
            <partial name="_LoginPartial.cshtml" />


        </div>
    </nav>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Trabalho Prático 2023 || Filipa Pimentel & Gonçalo Leite ||
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Programação Web/TrabalhoFinalRentCar/Views/Shared/_ManagerPartial.cshtml
@using Microsoft.AspNetCore.Identity
@using TrabalhoFinalRentCar.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager


@if (User.Identity.IsAuthenticated && User.IsInRole("Manager"))
{

    <a class="#" style="color: #FFFFFF;font-size: 14px;text-decoration: none;font-family:'Playfair Display';margin-left: 15px; margin-right: 15px;display:inline-block;"  asp-area="" asp-controller="User" asp-action="Employees">Employees</a>
    <a class="#" style="color: #FFFFFF;font-size: 14px;text-decoration: none;font-family:'Playfair Display';margin-left: 15px; margin-right: 15px;display:inline-block;" asp-area="" asp-controller="Rooms" asp-action="ManagePortfolio">Rooms Portfolio</a>


}