Projeto de Estágio/Clientes/Clientes/Controllers/LeadsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Clientes.Data;
using Clientes.Models;

namespace Clientes.Controllers
{
    public class LeadsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public LeadsController(ApplicationDbContext context)
        {
            _context = context;
        }

        //GET:Leads
        public async Task<IActionResult> Index(string TextoAPesquisar, int Quente=3)
        {
            if (TextoAPesquisar != null && Quente==3)
            {

                return View(await _context.Leads.Where(c => c.Nome.Contains(TextoAPesquisar)).ToListAsync());
            }
            var applicationDbContext = _context.Leads.Include(a => a.Quente);
            ViewData["QuenteId"] = new SelectList(_context.Estados, "EstadoId", "EstadoLeadNome");
            if(Quente == 1)
            {

                return View(await applicationDbContext.Where(c => c.Quente.EstadoLeadNome == "Quente").ToListAsync());

            }
            if(Quente == 2)
            {

                return View(await applicationDbContext.Where(c => c.Quente.EstadoLeadNome == "Frio").ToListAsync());

            }
            return View(await applicationDbContext.Where(c => c.Quente.EstadoLeadNome == "Quente" || c.Quente.EstadoLeadNome == "Frio").OrderBy(c => c.Nome).ToListAsync());
        }

        public async Task<IActionResult> Tabela(string TextoAPesquisar, int Nome, int Responsavel, int Email, int Telefone, int AFazer, int Estado, DateTime data1, DateTime data2, int datanova = 1)

        {
            ViewData["QuenteId"] = new SelectList(_context.Estados, "EstadoId", "EstadoLeadNome");
            var applicationDbContext = _context.Leads.Include(a => a.Quente);

            if (TextoAPesquisar != null)
            {
                return View(await applicationDbContext.Where(c => c.Nome.Contains(TextoAPesquisar)).ToListAsync());
            }

            if (Nome == 1)
            {
                return View(await applicationDbContext.OrderBy(c => c.Nome).ToListAsync());
            }

            if (Nome == 2)
            {

                return View(await applicationDbContext.OrderByDescending(c => c.Nome).ToListAsync());
            }

            if (Responsavel == 1)
            {
                return View(await applicationDbContext.OrderBy(c => c.Responsavel).ToListAsync());
            }

            if (Responsavel == 2)
            {

                return View(await applicationDbContext.OrderByDescending(c => c.Responsavel).ToListAsync());
            }

            if (Email == 1)
            {
                return View(await applicationDbContext.OrderBy(c => c.Email).ToListAsync());
            }

            if (Email == 2)
            {

                return View(await applicationDbContext.OrderByDescending(c => c.Email).ToListAsync());
            }

            if (Telefone== 1)
            {
                return View(await applicationDbContext.OrderBy(c => c.Telefone).ToListAsync());
            }

            if (Telefone == 2)
            {

                return View(await applicationDbContext.OrderByDescending(c => c.Telefone).ToListAsync());
            }
            if (AFazer == 1)
            {
                return View(await applicationDbContext.OrderBy(c => c.AFazer).ToListAsync());
            }

            if (AFazer == 2)
            {

                return View(await applicationDbContext.OrderByDescending(c => c.AFazer).ToListAsync());
            }
            if (Estado == 1)
            {
                return View(await applicationDbContext.OrderBy(c => c.Quente.EstadoLeadNome).ToListAsync());
            }

            if (Estado == 2)
            {

                return View(await applicationDbContext.OrderByDescending(c => c.Quente.EstadoLeadNome).ToListAsync());
            }
            if (datanova == 1)
            {

                return View(await applicationDbContext.OrderBy(c => c.Nome).ToListAsync());
            }

            ViewData["ClienteCamID"] = new SelectList(_context.Clientes, "Id", "Nome");
            return View(await _context.Leads.OrderBy(c => c.Nome).ToListAsync());
        }


        // GET: Leads/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Leads == null)
            {
                return NotFound();
            }
             ViewData["QuenteId"] = new SelectList(_context.Estados, "EstadoId", "EstadoLeadNome");


            var leads = await _context.Leads.Include(a => a.Quente)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leads == null)
            {
                return NotFound();
            }

            return View(leads);
        }

        // GET: Leads/Create
        public IActionResult Create()
        {
            ViewData["QuenteId"] = new SelectList(_context.Estados, "EstadoId", "EstadoLeadNome");

            return View();
        }

        // POST: Leads/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Responsavel,PrimeiroContacto,DataPrimeiroC,AFazer,EstadoLead,Reuniao,Proposta,Resultados,Observacoes,Detalhes,Email,Telefone,SetorAtividade,QuenteId")] Leads leads)
        {
            ModelState.Remove(nameof(leads.Quente));

            if (ModelState.IsValid)
            {
                _context.Add(leads);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["QuenteId"] = new SelectList(_context.Estados, "EstadoId", "EstadoLeadNome", leads.QuenteId);
            return View(leads);
        }

        // GET: Leads/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Leads == null)
            {
                return NotFound();
            }

            var leads = await _context.Leads.FindAsync(id);
            if (leads == null)
            {
                return NotFound();
            }
            ViewData["QuenteId"] = new SelectList(_context.Estados/*.Where(c => c.EstadoLeadNome.Equals("Quente") || c.EstadoLeadNome.Equals("Frio"))*/, "EstadoId", "EstadoLeadNome");
            return View(leads);
        }

        // POST: Leads/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Responsavel,PrimeiroContacto,DataPrimeiroC,AFazer,EstadoLead,Reuniao,Proposta,Resultados,Observacoes,Detalhes,Email,Telefone,SetorAtividade,QuenteId")] Leads leads)
        {
            ModelState.Remove(nameof(leads.Quente));
            if (id != leads.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(leads);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LeadsExists(leads.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["QuenteId"] = new SelectList(_context.Estados, "EstadoId", "EstadoLeadNome");
            return View(leads);
        }

        // GET: Leads/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Leads == null)
            {
                return NotFound();
            }

            var leads = await _context.Leads
                .FirstOrDefaultAsync(m => m.Id == id);
            if (leads == null)
            {
                return NotFound();
            }

            return View(leads);
        }

        // POST: Leads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Leads == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Leads'  is null.");
            }
            var leads = await _context.Leads.FindAsync(id);
            if (leads != null)
            {
                _context.Leads.Remove(leads);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LeadsExists(int id)
        {
          return _context.Leads.Any(e => e.Id == id);
        }

        public async Task<IActionResult> ListaClientesLeads(string TextoAPesquisar,int nome, int email, int telefone)
        {
            if (TextoAPesquisar != null)
            {
                return View(await _context.Leads.Where(c => c.Nome.Contains(TextoAPesquisar)).ToListAsync());
            }


            if (nome == 1)
            {
                return View(await _context.Leads.OrderBy(c => c.Nome).ToListAsync());
            }

            if (nome == 2)
            {

                return View(await _context.Leads.OrderByDescending(c => c.Nome).ToListAsync());
            }

            if (email == 1)
            {

Projeto de Estágio/Clientes/Clientes/Controllers/NotasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Clientes.Data;
using Clientes.Models;

namespace Clientes.Controllers
{
    public class NotasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NotasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Notas
        public async Task<IActionResult> Index()
        {
              return _context.Notas != null ? 
                          View(await _context.Notas.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Notas'  is null.");
        }

        // GET: Notas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Notas == null)
            {
                return NotFound();
            }

            var nota = await _context.Notas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nota == null)
            {
                return NotFound();
            }

            return View(nota);
        }

        // GET: Notas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Notas/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,TextoNota,Responsavel,DataRealizar")] Nota nota)
        {
            if (ModelState.IsValid)
            {
                _context.Add(nota);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(nota);
        }

        // GET: Notas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Notas == null)
            {
                return NotFound();
            }

            var nota = await _context.Notas.FindAsync(id);
            if (nota == null)
            {
                return NotFound();
            }
            return View(nota);
        }

        // POST: Notas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,TextoNota,Responsavel,DataRealizar")] Nota nota)
        {
            if (id != nota.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(nota);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NotaExists(nota.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(nota);
        }

        // GET: Notas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Notas == null)
            {
                return NotFound();
            }

            var nota = await _context.Notas
                .FirstOrDefaultAsync(m => m.Id == id);
            if (nota == null)
            {
                return NotFound();
            }

            return View(nota);
        }

        // POST: Notas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Notas == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Notas'  is null.");
            }
            var nota = await _context.Notas.FindAsync(id);
            if (nota != null)
            {
                _context.Notas.Remove(nota);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool NotaExists(int id)
        {
          return (_context.Notas?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Projeto de Estágio/Clientes/Clientes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClientesALista</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="shortcut icon" href="~/img/iconRoyalBlue.png" type="image/x-icon" />
</head>


<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
            <div class="container-fluid">
                <a class="navbar-brand " asp-area="" asp-controller="Home" asp-action="Index"  ></a>
                <a href="/Home/Index">
                    <img src="~/img/Alista_Digital_White_logo.png" alt="" width="200" height="65"/>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01" padding-left: 500px>
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item dropdown" width="200" height="65">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false" > <img src="~/img/usuarios.png"  width="45" height="20"/>Clientes</a>
                            
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Clientes" asp-action="ListaClientes"> <img src="~/img/reservar-usuario.png"  width="45" height="25"/>Clientes</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Clientes" asp-action="ListaContactos"> <img src="~/img/contact-mail.png"  width="45" height="25"/>Contactos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Clientes" asp-action="Custos"> <img src="~/img/contract.png"  width="45" height="25"/>Detalhes Contratos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="PdfFiles" asp-action="Details"> <img src="~/img/ficheiro-pdf.png" width="45" height="25" />Contratos PDFs</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Clientes" asp-action="Create"> <img src="~/img/page.png" width="45" height="25" />Novo Cliente</a>

                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> <img src="~/img/calendario.png"  width="45" height="25"/>Agendamentos</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Agendamentos" asp-action="ListaAgendamentos"> <img src="~/img/clipboard.png"  width="45" height="25"/>Agendamentos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Agendamentos" asp-action="Historico"> <img src="~/img/history.png"  width="45" height="25"/>Histórico</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Agendamentos" asp-action="Create"> <img src="~/img/page.png"  width="45" height="25"/>Novo Agendamento</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Agendamentos" asp-action="CreateLeads"> <img src="~/img/page.png" width="45" height="25" />Novo Agendamento (lead)</a>

                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> <img src="~/img/documento-assinado.png" width="45" height="25" />Leads</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Leads" asp-action="Index"> <img src="~/img/clipboard.png"  width="45" height="25"/>Leads</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Leads" asp-action="LeadsConcluidas"> <img src="~/img/done.png" width="45" height="25" />Histórico</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Leads" asp-action="ClientesLeadsCards"> <img src="~/img/recruitment.png"  width="45" height="25"/>Possiveis Clientes</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Leads" asp-action="Create"> <img src="~/img/page.png" width="45" height="25" />Nova Lead</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> <img src="~/img/megafone.png" width="45" height="25" /> Campanhas</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Campanhas" asp-action="ListaCampanhas"> <img src="~/img/clipboard.png"  width="45" height="25"/>Campanhas</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Campanhas" asp-action="Create"> <img src="~/img/page.png"  width="45" height="25"/>Nova Campanha</a>
                               </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> <img src="~/img/marcador-de-livro.png" width="45" height="25" /> Notas</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Notas" asp-action="Index"> <img src="~/img/notes.png" width="45" height="25" />Notas</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Notas" asp-action="Create"> <img src="~/img/page.png" width="45" height="25" />Nova Nota</a>
                            </div>
                        </li>
                       
                  
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
        
   

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>


<style>
    img {
       
        /*padding-right: 30px;*/
       
        padding-right: 20px;
    }
    li{
        padding-rigth: 50px;
        font-size: 20px ;
        width :200;
        height :65;
    }

    div {
        
        padding-top: 5px;
        padding-bottom: 5px;
    
    }

    body {
        min-height: 80vh;
    }

    footer {
        margin-top: ??px;
        margin-bottom : 20px;
    }

    .dropdown-item:active {
        color: var(--bs-dropdown-link-active-color);
        text-decoration: none;
        background-color: #2196f3;
        color: aliceblue;
        background-image: var(--bs-gradient);
    }
    
</style>

Projeto de Estágio/Clientes/Clientes/Views/Shared/_LayoutAgendamentos.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ClientesALista</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="shortcut icon" href="~/img/darkOrange.png" type="image/x-icon" />
</head>


<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark" style="background-color:darkorange; color:aliceblue">
            <div class="container-fluid">
                <a class="navbar-brand " asp-area="" asp-controller="Home" asp-action="Index"></a>
                <a href="/Home/Index">
                    <img src="~/img/Alista_Digital_White_logo.png" alt="" width="200" height="65" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01" padding-left: 500px>
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item dropdown" width="200" height="65">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> <img src="~/img/cliente (2).png" width="45" height="20" />Clientes</a>

                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Clientes" asp-action="ListaClientes"> <img src="~/img/reservar-usuario.png" width="45" height="25" />Lista de Clientes</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Clientes" asp-action="ListaContactos"> <img src="~/img/contact-mail.png" width="45" height="25" />Contactos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Clientes" asp-action="Custos"> <img src="~/img/contract.png" width="45" height="25" />Contratos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="PdfFiles" asp-action="Details"> <img src="~/img/ficheiro-pdf.png" width="45" height="25" />Lista PDFs</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Clientes" asp-action="Create"> <img src="~/img/page.png" width="45" height="25" />Novo Cliente</a>

                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> <img src="~/img/agenda (2).png" width="45" height="25" />Agendamentos</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Agendamentos" asp-action="ListaAgendamentos"> <img src="~/img/clipboard.png" width="45" height="25" />Lista de Agendamentos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Agendamentos" asp-action="Historico"> <img src="~/img/history.png" width="45" height="25" />Histórico</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Agendamentos" asp-action="Create"> <img src="~/img/page.png" width="45" height="25" />Novo Agendamento</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Agendamentos" asp-action="CreateLeads"> <img src="~/img/page.png" width="45" height="25" />Novo Agendamento (lead)</a>

                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> <img src="~/img/checklist.png" width="45" height="25" />Leads</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Leads" asp-action="Index"> <img src="~/img/clipboard.png" width="45" height="25" />Lista das Leads</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Leads" asp-action="LeadsConcluidas"> <img src="~/img/done.png" width="45" height="25" />Leads Concluidas</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Leads" asp-action="ClientesLeadsCards"> <img src="~/img/recruitment.png" width="45" height="25" />Lista de Possiveis Clientes</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Leads" asp-action="Create"> <img src="~/img/page.png" width="45" height="25" />Nova Lead</a>
                            
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> <img src="~/img/bullhorn (3).png" width="45" height="25" /> Campanhas</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Campanhas" asp-action="ListaCampanhas"> <img src="~/img/clipboard.png" width="45" height="25" />Lista de Campanhas</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Campanhas" asp-action="Create"> <img src="~/img/page.png" width="45" height="25" />Nova Campanha</a>
                            </div>
                        </li>
                           <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false"> <img src="~/img/notas.png" width="45" height="25" /> Notas</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" asp-area="" asp-controller="Notas" asp-action="Index"> <img src="~/img/notes.png" width="45" height="25" />Lista de Notas</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Notas" asp-action="Create"> <img src="~/img/page.png" width="45" height="25" />Nova Nota</a>
                            </div>
                        </li>



                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <div class="position-relative">

    </div>
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; ||A Lista Digital ||
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @* <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>


<style>
    img {
        /*padding-right: 30px;*/

        padding-right: 20px;
    }

    li {
        padding-rigth: 50px;
        font-size: 20px;
        width: 200;
        height: 65;
    }

    div {
        padding-top: 5px;
        padding-bottom: 5px;
    }

    body {
        min-height: 150vh;
    }

    footer {
        margin-top: ???px;
    }

    .dropdown-item:active {
        color: var(--bs-dropdown-link-active-color);
        text-decoration: none;
        background-color: darkorange;
        color: aliceblue;
        background-image: var(--bs-gradient);
    }

   
</style>