Projeto de Estágio/Clientes/Clientes/Models/Campanha.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Drawing;
using System.Xml.Linq;

namespace Clientes.Models
{
    public class Campanha
    {
        public int CampanhaId { get; set; }

        [Display(Name = "Plataforma", Prompt = "Introduza a Plataforma da Campanha*")]
        public string Plataforma { get; set; }
        [DataType(DataType.Date)]
        public DateTime? Data { get; set; }
        [Display(Name = "Duração")]
        [NotMapped]
        public TimeOnly? Duracao { get; set; }
        [Display(Name = "Investimento monetário", Prompt = "Investimento*")]
        public int? Investimento { get; set; }
        [Display(Name = "Interações", Prompt = "Número de Interações*")]
        public string? Interacao { get; set; }
        [Display(Name = "Descrição", Prompt = "Descrição*")]
        public string? Descricao { get; set; }
        [Display(Name = "Leads", Prompt = "Leads*")]
        public string? Leads { get; set; }
        [Display(Name = "Online", Prompt = "Online")]
        public bool Online { get; set; } = true;
        [Display(Name = "Cliente", Prompt = "Cliente")]
        public string? ClienteCampanha { get; set; }
        [Display(Name = "Responsável", Prompt = "Responsável")]
        public string Responsavel { get; set; }

    }
}

Projeto de Estágio/Clientes/Clientes/Controllers/CampanhasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Clientes.Data;
using Clientes.Models;

namespace Clientes.Controllers
{
    public class CampanhasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CampanhasController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Campanhas
        public async Task<IActionResult> Index(string TextoAPesquisar,int Plataforma, int Data, int Investimento, int Interacao, int Leads, DateTime data1, DateTime data2, int datanova=1)

        {

            if (TextoAPesquisar != null)
            {
                return View(await _context.Campanhas.Where(c => c.Plataforma.Contains(TextoAPesquisar)).ToListAsync());
            }

            if (Plataforma == 1)
            {
                return View(await _context.Campanhas.OrderBy(c => c.Plataforma).ToListAsync());
            }

            if (Plataforma == 2)
            {

                return View(await _context.Campanhas.OrderByDescending(c => c.Plataforma).ToListAsync());
            }

            if (Data == 1)
            {
                return View(await _context.Campanhas.OrderBy(c => c.Data).ToListAsync());
            }

            if (Data == 2)
            {

                return View(await _context.Campanhas.OrderByDescending(c => c.Data).ToListAsync());
            }

            if (Investimento == 1)
            {
                return View(await _context.Campanhas.OrderBy(c => c.Investimento).ToListAsync());
            }

            if (Investimento == 2)
            {

                return View(await _context.Campanhas.OrderByDescending(c => c.Investimento).ToListAsync());
            }

            if (Interacao == 1)
            {
                return View(await _context.Campanhas.OrderBy(c => c.Interacao).ToListAsync());
            }

            if (Interacao == 2)
            {

                return View(await _context.Campanhas.OrderByDescending(c => c.Interacao).ToListAsync());
            }
            if (Leads == 1)
            {
                return View(await _context.Campanhas.OrderBy(c => c.Leads).ToListAsync());
            }

            if (Leads == 2)
            {

                return View(await _context.Campanhas.OrderByDescending(c => c.Leads).ToListAsync());
            }
            if (datanova == 1)
            {

                return View(await _context.Campanhas.ToListAsync());
            }

            ViewData["ClienteCamID"] = new SelectList(_context.Clientes.OrderBy(c => c.Nome), "Id", "Nome");
            return View(await _context.Campanhas.Where(c => c.Data > DateTime.Now && c.Data >= data1 && c.Data <= data2).OrderBy(c => c.Plataforma).ToListAsync());
        }

        // GET: Campanhas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Campanhas == null)
            {
                return NotFound();
            }

            var campanha = await _context.Campanhas
                .FirstOrDefaultAsync(m => m.CampanhaId == id);
            if (campanha == null)
            {
                return NotFound();
            }

            ViewData["ClienteCamID"] = new SelectList(_context.Clientes, "Id", "Nome");

            return View(campanha);
        }

        // GET: Campanhas/Create
        public IActionResult Create()
        {
            //var dataList = _context.Clientes;
            

            //var selectList = new SelectList(dataList, "Id", "Nome");

            //ViewData["ClienteCamID"] = selectList;
            ViewData["ClienteCamID"] = new SelectList(_context.Clientes, "Id", "Nome");
            return View();
        }

        // POST: Campanhas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CampanhaId,Plataforma,Data,Investimento,Responsavel,Interacao,Leads,Descricao,ClienteCampanha")] Campanha campanha)
        {
            
            
            if (ModelState.IsValid)
            {
                campanha.Data= campanha.Data;
                _context.Add(campanha);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            
            
            return View(campanha);
        }

        // GET: Campanhas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Campanhas == null)
            {
                return NotFound();
            }

            var campanha = await _context.Campanhas.FindAsync(id);
            if (campanha == null)
            {
                return NotFound();
            }

            ViewData["ClienteCamID"] = new SelectList(_context.Clientes, "Id", "Nome");
            return View(campanha);
        }

        // POST: Campanhas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CampanhaId,Plataforma,Data,Responsavel,Investimento,Interacao,Leads,Descricao,Online,ClienteCampanha")] Campanha campanha)
        {

           
            if (id != campanha.CampanhaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(campanha);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CampanhaExists(campanha.CampanhaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(campanha);
        }

        // GET: Campanhas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Campanhas == null)
            {
                return NotFound();
            }

            var campanha = await _context.Campanhas
                .FirstOrDefaultAsync(m => m.CampanhaId == id);
            if (campanha == null)
            {
                return NotFound();
            }

            return View(campanha);
        }

        // POST: Campanhas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Campanhas == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Campanha'  is null.");
            }
            var campanha = await _context.Campanhas.FindAsync(id);
            if (campanha != null)
            {
                _context.Campanhas.Remove(campanha);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CampanhaExists(int id)
        {
          return _context.Campanhas.Any(e => e.CampanhaId == id);
        }


        public async Task<IActionResult> ListaCampanhas(string TextoAPesquisar, int Plataforma, int Data, int Investimento, int Interacao, int Leads, DateTime data1, DateTime data2, int Ativa, int datanova = 1)

        {
            ViewData["ClienteCamID"] = new SelectList(_context.Clientes, "Id", "Nome");

            if (TextoAPesquisar != null)
            {
                return View(await _context.Campanhas.Where(c => c.Plataforma.Contains(TextoAPesquisar)).ToListAsync());
            }

            if (Plataforma == 1)
            {
                return View(await _context.Campanhas.OrderBy(c => c.Plataforma).ToListAsync());
            }

            if (Plataforma == 2)
            {

                return View(await _context.Campanhas.OrderByDescending(c => c.Plataforma).ToListAsync());
            }

            if (Ativa == 1)
            {
                return View(await _context.Campanhas.Where(c => c.Online == true).ToListAsync());
            }

            if (Ativa == 2)
            {

                return View(await _context.Campanhas.Where(c => c.Online == false).ToListAsync());
            }

            if (Data == 1)
            {
                return View(await _context.Campanhas.OrderBy(c => c.Data).ToListAsync());
            }

            if (Data == 2)
            {

                return View(await _context.Campanhas.OrderByDescending(c => c.Data).ToListAsync());
            }

            if (Investimento == 1)
            {
                return View(await _context.Campanhas.OrderBy(c => c.Investimento).ToListAsync());
            }

            if (Investimento == 2)
            {

                return View(await _context.Campanhas.OrderByDescending(c => c.Investimento).ToListAsync());
            }

            if (Interacao == 1)
            {
                return View(await _context.Campanhas.OrderBy(c => c.Interacao).ToListAsync());
            }

            if (Interacao == 2)
            {

                return View(await _context.Campanhas.OrderByDescending(c => c.Interacao).ToListAsync());
            }
            if (Leads == 1)
            {
                return View(await _context.Campanhas.OrderBy(c => c.Leads).ToListAsync());
            }

Projeto de Estágio/Clientes/Clientes/Views/Campanhas/Create.cshtml
@model Clientes.Models.Campanha

@{
    ViewData["Title"] = "Nova Campanha";
    Layout = "~/Views/Shared/_LayoutCampanhas.cshtml";
}



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.0/js/bootstrap.min.js"></script>
    <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
    <!------ Include the above in your HEAD tag ---------->

    <script type="text/javascript" src="http://www.clubdesign.at/floatlabels.js"></script>

    <div class="container">
        <div class="row centered-form">
            <div class="col-xs-12 col-sm-8 col-md-4 col-sm-offset-2 col-md-offset-4">
                <div class="panel panel-default" style="block-size:auto; padding-top:0px">
                    <div class="panel-heading" style="background-color:mediumpurple">
                        <h3 class="panel-title" style="color:aliceblue">Nova Campanha</h3>
                    </div>
                    <div class="panel-body">
                        <form asp-action="Create">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group" style="visibility:hidden">
                            </div>
                            <div class="form-group">
                                <div class="form-floating mb-3">
                                    <input asp-for="Plataforma" class="form-control" style="background-color:white" />
                                    <label for="floatingInput" style="color:grey">Plataforma</label>
                                    <span asp-validation-for="Plataforma" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">

                                <input asp-for="Data" class="form-control" />
                                <span asp-validation-for="Data" class="text-danger"></span>
                            </div>
                            <div class="form-group">
                                <div class="form-floating mb-3">
                                    <input asp-for="Investimento" class="form-control" style="background-color:white" />
                                    <label for="floatingInput" style="color:grey">Investimento</label>
                                    <span asp-validation-for="Investimento" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="form-floating mb-3">
                                    <input asp-for="Responsavel" class="form-control" style="background-color:white" />
                                    <label for="floatingInput" style="color:grey">Responsável</label>
                                    <span asp-validation-for="Responsavel" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="form-floating mb-3">
                                    <input asp-for="Interacao" class="form-control" style="background-color:white" />
                                    <label for="floatingInput" style="color:grey">Interação</label>
                                    <span asp-validation-for="Interacao" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="form-floating mb-3">
                                    <input asp-for="Leads" class="form-control" style="background-color:white" />
                                    <label for="floatingInput" style="color:grey">Leads</label>
                                    <span asp-validation-for="Leads" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="form-floating mb-3">
                                    <input asp-for="Descricao" class="form-control" style="background-color:white" />
                                    <label for="floatingInput" style="color:grey">Descrição</label>
                                    <span asp-validation-for="Descricao" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="form-floating mb-3">
                                    <input asp-for="ClienteCampanha" class="form-control" style="background-color:white" />
                                    <label for="floatingInput" style="color:grey">Cliente</label>
                                    <span asp-validation-for="ClienteCampanha" class="text-danger"></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <input type="submit" value="Criar" class="btn btn-sm" style="background-color:aliceblue; color:mediumpurple" />
                                <a asp-action="Index" class="btn btn-sm" style="background-color:aliceblue; color:mediumpurple">Voltar</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
}
    <style>
        body {
            /* Safari 4-5, Chrome 1-9 */
            background: -webkit-gradient(radial, center center, 0, center center, 460, from(#ffff66), to(#2F2727));
            /* Safari 5.1+, Chrome 10+ */
            background: -webkit-radial-gradient(circle, mediumpurple, white);
            /* Firefox 3.6+ */
            background: -moz-radial-gradient(circle, #ffff66, white);
            /* IE 10 */
            background: -ms-radial-gradient(circle, #ffff66, white);
            height: 600px;
        }

        .centered-form {
            margin-top: 60px;
        }

            .centered-form .panel {
                background: rgba(255, 255, 255, 0.8);
                box-shadow: rgba(0, 0, 0, 0.3) 20px 20px 20px;
            }

       .label-floatlabel {
            font-weight: bold;
            color: #46b8da;
            font-size: 11px;
        }

        

    </style>

Projeto de Estágio/Clientes/Clientes/Views/Campanhas/Delete.cshtml
@model Clientes.Models.Campanha

@{
    ViewData["Title"] = "Eliminar Campanha";
    Layout = "~/Views/Shared/_LayoutCampanhas.cshtml";
}

<h1>Eliminar</h1>

<h3>Tem a certeza que quer eliminar esta Campanha?</h3>
<div>
    
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Plataforma)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Plataforma)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Data)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Data.Value.Day)/@Html.DisplayFor(model => model.Data.Value.Month)/@Html.DisplayFor(model => model.Data.Value.Year)


        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Investimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Investimento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Interacao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Interacao)
        </dd>
            <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Responsavel)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Responsavel)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Leads)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Leads)
        </dd>
          <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
    </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CampanhaId" />
        <input type="submit" value="Eliminar" class="btn btn-sm btn-danger" /> |
        <a asp-action="Index" class="btn btn-sm" style="margin:3px;  background-color:mediumpurple; color:aliceblue">Cancelar</a>
    </form>
</div>

Projeto de Estágio/Clientes/Clientes/Views/Campanhas/ListaCampanhas.cshtml
@model IEnumerable<Clientes.Models.Campanha>

@{
    ViewData["Title"] = "Lista Campanhas";
    Layout = "~/Views/Shared/_LayoutCampanhas.cshtml";
}

<h1 class="pb-2 border-bottom">
    <span class="badge rounded-pill" style="background-color:mediumpurple; color:aliceblue"> Campanhas </span>
    <a asp-action="Create" class="btn btn-sm" style="color:mediumpurple"> Nova Campanha </a>
</h1>





<form method="post">

    

    
    <input class="card-text" type="text" id="TextoAPesquisar" name="TextoAPesquisar" placeholder="Plataforma">



    <input class="btn btn-sm my-2 my-sm-0" style="background-color:mediumpurple; color:aliceblue" type="image" src="~/img/lupa.png" width="40" height="30" alt="Submit" asp-route-Datanova="0" />


    <a asp-action="ListaCampanhas" class="btn btn-sm" style="background-color:mediumpurple; color:aliceblue" height="500" width="500"> TODOS </a>
    <button id="btnGroupDrop1" type="button" class="btn  btn-sm dropdown-toggle show" style="background-color:mediumpurple; color:aliceblue" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></button>
    <div class="dropdown-menu " aria-labelledby="btnGroupDrop1" style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate3d(0px, 52px, 0px);background-color:aliceblue; color:mediumpurple" data-popper-placement="bottom-start">
        <a asp-controller="Campanhas" asp-action="ListaCampanhas" asp-route-Ativa="1" class="btn btn-sm px-4 gap-3" style="margin:3px;  background-color:mediumpurple; color:aliceblue"> Ativas </a>
        <a asp-controller="Campanhas" asp-action="ListaCampanhas" asp-route-Ativa="2" class="btn btn-sm px-4 gap-3" style="margin:3px;  background-color:mediumpurple; color:aliceblue"> Inativas </a>
    </div>
    <a asp-action="Index" class="btn btn-sm" style="background-color:mediumpurple; color:aliceblue" height="50px" width="50px"> ⇆ </a>
    
</form>


@*<div class="container">
    @foreach (var item in Model) {
    <div class="row g-3">
            <div class="col-md-6 ">
            <div class="well well-sm">
                <div class="row">
                    
                    <div class="col-xs-9 col-md-9 section-box">
                        <h2>
                                @Html.DisplayFor(modelItem => item.Plataforma) <a href="http://bootsnipp.com/" target="_blank">
                                <span class="glyphicon glyphicon-new-window">
                                </span>
                            </a>
                        </h2>
                        <p>
                                @Html.DisplayFor(modelItem => item.Descricao)
                        </p>
                        <hr />
                        <div class="row rating-desc">
                            <div class="col-md-12">
                                <span class="glyphicon glyphicon-heart"></span><span class="glyphicon glyphicon-heart">
                                </span><span class="glyphicon glyphicon-heart"></span><span class="glyphicon glyphicon-heart">
                                    </span><span class="glyphicon glyphicon-heart"></span>Clicks: (@Html.DisplayFor(modelItem => item.Interacao))<span class="separator">|</span>
                                    <span class="glyphicon glyphicon-comment"></span>(Investimento: @Html.DisplayFor(modelItem => item.Investimento) €)
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
       </div>
       }
</div>*@


<div class="row align-items-stretch g-3">
    @foreach (var item in Model) {
        @if(item.Online == true) {
            <div class="col-12 col-md-6 col-lg-4" @*class="note-has-grid row"*@>



                <div class="card  order-card m-0 h-100 note-has-grid row" style="background-color:mediumpurple; color:aliceblue">


                    <div class="card-block " style=" color:aliceblue">

                        <h3 class="m-b-20">@Html.DisplayFor(modelItem => item.Plataforma) - <img src="~/img/roundGreen.png" width="50" height="30" /></h3>

                        <h6 class="text-right"><i class="fa fa-cart-plus f-left"></i><span>@Html.DisplayFor(modelItem => item.Descricao)</span></h6>
                        <p class="m-b-0">Clicks<span class="f-right">@Html.DisplayFor(modelItem => item.Interacao)</span></p>
                        <p class="m-b-0">Responsável<span class="f-right">@Html.DisplayFor(modelItem => item.Responsavel)</span></p>
                        <p class="m-b-0">Investimento<span class="f-right">@Html.DisplayFor(modelItem => item.Investimento) €</span></p>
                        <a asp-action="Details" asp-route-id="@item.CampanhaId" class="btn btn-sm btn-info"> Detalhes </a>
                        <a asp-action="Edit" asp-route-id="@item.CampanhaId" class="btn btn-sm btn-success"> Editar </a>
                    </div>
                </div>

            </div>
        }
        else {
            <div class="col-12 col-md-6 col-lg-4" @*class="note-has-grid row"*@>



                <div class="card  order-card m-0 h-100 note-has-grid row" style="background-color:mediumpurple; color:aliceblue">


                    <div class="card-block " style=" color:aliceblue">

                        <h3 class="m-b-20">@Html.DisplayFor(modelItem => item.Plataforma) - <img src="~/img/roundRed.png" width="50" height="30" /></h3>

                        <h6 class="text-right"><i class="fa fa-cart-plus f-left"></i><span>@Html.DisplayFor(modelItem => item.Descricao)</span></h6>
                        <p class="m-b-0">Clicks<span class="f-right">@Html.DisplayFor(modelItem => item.Interacao)</span></p>
                        <p class="m-b-0">Responsável<span class="f-right">@Html.DisplayFor(modelItem => item.Responsavel)</span></p>
                        <p class="m-b-0">Investimento<span class="f-right">@Html.DisplayFor(modelItem => item.Investimento) €</span></p>
                        <a asp-action="Details" asp-route-id="@item.CampanhaId" class="btn btn-sm btn-info"> Detalhes </a>
                        <a asp-action="Edit" asp-route-id="@item.CampanhaId" class="btn btn-sm btn-success"> Editar </a>
                    </div>
                </div>

            </div>
        }

       
    }
</div>


<style>
   

 


    .order-card {
        color: #fff;
    }

    .bg-c-blue {
        background: linear-gradient(45deg,#4099ff,#73b4ff);
    }

    .bg-c-green {
        background: linear-gradient(45deg,#2ed8b6,#59e0c5);
    }

    .bg-c-yellow {
        background: linear-gradient(45deg,#FFB64D,#ffcb80);
    }

    .bg-c-pink {
        background: linear-gradient(45deg,#FF5370,#ff869a);
    }


    .card {
        border-radius: 5px;
        -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);
        box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);
        border: none;
        margin-bottom: 30px;
        -webkit-transition: all 0.3s ease-in-out;
        transition: all 0.3s ease-in-out;
    }

        .card .card-block {
            padding: 25px;
        }

    .order-card i {
        font-size: 26px;
    }

    .f-left {
        float: left;
    }

    .f-right {
        float: right;
    }

    body {
        background: #edf1f5;
        
    }

    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: border-box;
        border: 0 solid transparent;
        border-radius: 0;
    }

    .card {
        margin-bottom: 30px;
    }

    .card-body {
        flex: 1 1 auto;
        padding: 1.57rem;
    }

    .note-has-grid .nav-link {
        padding: .5rem
    }

    .note-has-grid .single-note-item .card {
        border-radius: 10px
    }

    .note-has-grid .single-note-item .favourite-note {
        cursor: pointer
    }

    .note-has-grid .single-note-item .side-stick {
        position: absolute;
        width: 3px;
        height: 35px;
        left: 0;
        background-color: rgba(82, 95, 127, .5)
    }

    .note-has-grid .single-note-item .category-dropdown.dropdown-toggle:after {
        display: none
    }

    .note-has-grid .single-note-item .category [class*=category-] {
        height: 15px;
        width: 15px;
        display: none
    }

        .note-has-grid .single-note-item .category [class*=category-]::after {
            content: "\f0d7";
            font: normal normal normal 14px/1 FontAwesome;
            font-size: 12px;
            color: #fff;
            position: absolute
        }

    .note-has-grid .single-note-item .category .category-business {
        background-color: rgba(44, 208, 126, .5);
        border: 2px solid #2cd07e
    }

    .note-has-grid .single-note-item .category .category-social {
        background-color: rgba(44, 171, 227, .5);
        border: 2px solid #2cabe3
    }

    .note-has-grid .single-note-item .category .category-important {
        background-color: rgba(255, 80, 80, .5);
        border: 2px solid #ff5050
    }

    .note-has-grid .single-note-item.all-category .point {
        color: rgba(82, 95, 127, .5)
    }

    .note-has-grid .single-note-item.note-business .point {
        color: rgba(44, 208, 126, .5)
    }

    .note-has-grid .single-note-item.note-business .side-stick {
        background-color: rgba(44, 208, 126, .5)
    }

    .note-has-grid .single-note-item.note-business .category .category-business {
        display: inline-block
    }

    .note-has-grid .single-note-item.note-favourite .favourite-note {
        color: #ffc107
    }

    .note-has-grid .single-note-item.note-social .point {
        color: rgba(44, 171, 227, .5)
    }

    .note-has-grid .single-note-item.note-social .side-stick {
        background-color: rgba(44, 171, 227, .5)
    }

    .note-has-grid .single-note-item.note-social .category .category-social {
        display: inline-block
    }

    .note-has-grid .single-note-item.note-important .point {
        color: rgba(255, 80, 80, .5)
    }

    .note-has-grid .single-note-item.note-important .side-stick {
        background-color: rgba(255, 80, 80, .5)
    }

    .note-has-grid .single-note-item.note-important .category .category-important {
        display: inline-block
    }

    .note-has-grid .single-note-item.all-category .more-options,
    .note-has-grid .single-note-item.all-category.note-favourite .more-options {
        display: block
    }

    .note-has-grid .single-note-item.all-category.note-business .more-options,
    .note-has-grid .single-note-item.all-category.note-favourite.note-business .more-options,
    .note-has-grid .single-note-item.all-category.note-favourite.note-important .more-options,
    .note-has-grid .single-note-item.all-category.note-favourite.note-social .more-options,
    .note-has-grid .single-note-item.all-category.note-important .more-options,
    .note-has-grid .single-note-item.all-category.note-social .more-options {
        display: none
    }

</style>