Projeto de Estágio/Clientes/Clientes/Controllers/ClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Clientes.Data;
using Clientes.Models;
using System.Runtime.InteropServices;
using Microsoft.AspNetCore.Hosting;
using IHostingEnvironment = Microsoft.AspNetCore.Hosting.IHostingEnvironment;
using Microsoft.AspNetCore.Identity;
using Microsoft.Extensions.Hosting.Internal;
using Clientes.Data.Migrations;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace Clientes.Controllers
{
    public class ClientesController : Controller
    {
        
        private readonly ApplicationDbContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly IHostingEnvironment _hostingEnv;

        

        public ClientesController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment, IHostingEnvironment hostingEnv)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _hostingEnv = hostingEnv;
        }

        // GET: Clientes
        public async Task<IActionResult> Index(string TextoAPesquisar, string TextoAPesquisarTag, int Nome, int Servico, int Localizacao, int Morada,int Tags,int Lista)
        {





            if (TextoAPesquisar != null)
            {

                return View(await _context.Clientes.Where(c => c.Nome.Contains(TextoAPesquisar)|| c.NomeComercial.Contains(TextoAPesquisar) || c.Localidade.Contains(TextoAPesquisar)).OrderBy(c => c.Nome).ToListAsync());
            }
            

            if (TextoAPesquisarTag != null)
            {
                return View(await _context.Clientes.Where(c => c.Tags.Contains(TextoAPesquisarTag)).OrderBy(c => c.Tags).ToListAsync());
            }

            var applicationDbContext = _context.Agendamentos.Include(a => a.Cliente);


            if (Nome == 1)
            {
                return this.View(await _context.Clientes.OrderBy(c => c.Nome).ToListAsync());
            }
           

            if (Nome == 2)
            {

                return View(await _context.Clientes.OrderByDescending(c => c.Nome).ToListAsync());
            }

            if (Servico == 1)
            {
                return View(await _context.Clientes.OrderBy(c => c.Representante).ToListAsync());
            }

            if (Servico == 2)
            {

                return View(await _context.Clientes.OrderByDescending(c => c.Representante).ToListAsync());
            }

            if (Localizacao == 1)
            {
                return View(await _context.Clientes.OrderBy(c => c.Localidade).ToListAsync());
            }

            if (Localizacao == 2)
            {

                return View(await _context.Clientes.OrderByDescending(c => c.Localidade).ToListAsync());
            }

            if (Morada == 1)
            {
                return View(await _context.Clientes.OrderBy(c => c.Morada).ToListAsync());
            }

            if (Morada == 2)
            {

                return View(await _context.Clientes.OrderByDescending(c => c.Morada).ToListAsync());
            }
            if (Tags == 1)
            {
                return View(await _context.Clientes.OrderBy(c => c.Tags).ToListAsync());
            }

            if (Tags == 2)
            {

                return View(await _context.Clientes.OrderByDescending(c => c.Tags).ToListAsync());
            }

            if (Lista == 1)
            {
                return this.View(await _context.Clientes.Where(c => c.ALista == true && c.AListaDigital == false).OrderBy(c => c.Nome).ToListAsync());
            }


            if (Lista == 2)
            {

                return this.View(await _context.Clientes.Where(c => c.ALista == false && c.AListaDigital == true).OrderBy(c => c.Nome).ToListAsync());
            }

            if (Lista == 3)
            {
                return this.View(await _context.Clientes.Where(c => c.ALista == true && c.AListaDigital == true).OrderBy(c => c.Nome).ToListAsync());
            }


            return View(await _context.Clientes.OrderBy(c => c.Nome).ToListAsync());
        }

        // GET: Clientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes
                .Include(c => c.CPagamento)
                .Include(c => c.EnvioFatura)
                .Include(c => c.MPagamento)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (cliente == null)
            {
                return NotFound();
            }
            ViewData["CPagamentoId"] = new SelectList(_context.Condicoes, "CondicoesId", "Condicoes");
            ViewData["EnvioFaturaId"] = new SelectList(_context.EnvioFaturas, "FaturaId", "Fatura");
            ViewData["MPagamentoId"] = new SelectList(_context.MetodosPagamento, "MetodoId", "Metodo");

            return View(cliente);
        }

        // GET: Clientes/Create
        public IActionResult Create()
        {
            ViewData["CPagamentoId"] = new SelectList(_context.Condicoes, "CondicoesId", "Condicoes");
            ViewData["EnvioFaturaId"] = new SelectList(_context.EnvioFaturas, "FaturaId", "Fatura");
            ViewData["MPagamentoId"] = new SelectList(_context.MetodosPagamento, "MetodoId", "Metodo");
            return View();
        }

        // POST: Clientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(string? nome, string? email, int telefone, [Bind("Id,Nome,NomeComercial,Morada,Localidade,CodigoPostal,Distrito,Representante,Email,Telefone,Telemovel,Website,NIF,PlanoContratado,ALista,AListaDigital,Rs,Site,Fotografia,CPagamentoId,MPagamentoId,EnvioFaturaId,PagamentosOnline,VivaWallet,ContratoDPD,Tags,DataFaturacao,UltimaVisita,Necessidade,DataAdesao,DataFim,Custo,PdfFile,Observacoes")] Cliente cliente)
        {
            ModelState.Remove(nameof(cliente.CPagamento));
            ModelState.Remove(nameof(cliente.MPagamento));
            ModelState.Remove(nameof(cliente.EnvioFatura));


            var cliente1 = new Cliente();
            cliente1.Nome = nome;
            cliente1.Email = email;
            cliente1.Telefone = telefone;

            if (cliente.PdfFile != null)
            {
 

                if(cliente.Pdf != null)
                {


                    using var dataStream = new MemoryStream();



                    await cliente.PdfFile.CopyToAsync(dataStream);
                    cliente.Pdf = dataStream.ToArray();

                    string rootPath = _hostingEnv.WebRootPath.Replace(@"\\", "/");
                    string dirPath = String.Format("{0}/pdf", rootPath);
                    string fileName = "random.pdf";
                    string filePath = String.Format("{0}/pdf/{1}", rootPath, fileName);
                    using (MemoryStream ms = new MemoryStream(cliente.Pdf))
                    {
                        bool directoryExists = Directory.Exists(dirPath);
                        if (directoryExists != true)
                        {
                            Directory.CreateDirectory(dirPath);
                        }

                        using var stream = System.IO.File.Create(filePath);
                        await cliente.PdfFile.CopyToAsync(stream);


                    }
                }

                
                

                if (nome == null)
                {
                    if (ModelState.IsValid)
                    {


                        _context.Add(cliente1);
                        await _context.SaveChangesAsync();
                        return RedirectToAction(nameof(Index));
                    }
                    
                }

            }


            if (ModelState.IsValid)
                {


                

                    _context.Add(cliente);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                ViewData["CPagamentoId"] = new SelectList(_context.Condicoes, "CondicoesId", "Condicoes", cliente1.CPagamentoId);
                ViewData["EnvioFaturaId"] = new SelectList(_context.EnvioFaturas, "FaturaId", "Fatura", cliente1.EnvioFaturaId);
                ViewData["MPagamentoId"] = new SelectList(_context.MetodosPagamento, "MetodoId", "Metodo", cliente1.MPagamentoId);
                return View(cliente);
            
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Clientes == null)
            {
                return NotFound();
            }

            var cliente = await _context.Clientes.FindAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            ViewData["CPagamentoId"] = new SelectList(_context.Condicoes, "CondicoesId", "Condicoes", cliente.CPagamentoId);
            ViewData["EnvioFaturaId"] = new SelectList(_context.EnvioFaturas, "FaturaId", "Fatura", cliente.EnvioFaturaId);
            ViewData["MPagamentoId"] = new SelectList(_context.MetodosPagamento, "MetodoId", "Metodo", cliente.MPagamentoId);
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]

Projeto de Estágio/Clientes/Clientes/Controllers/PdfFilesController.cs
using Clientes.Data.Migrations;
using Microsoft.AspNetCore.Mvc;
using Clientes.Models;
using System.Configuration;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Clientes.Data;
using PdfFiles = Clientes.Models.PdfFiles;
using Microsoft.Extensions.Hosting.Internal;


namespace Clientes.Controllers
{
    public class PdfFilesController : Controller

    {
        [Obsolete]
        IWebHostEnvironment _hostingEnvironment = null;
        private  ApplicationDbContext _context;

        public PdfFilesController(Microsoft.AspNetCore.Hosting.IWebHostEnvironment hostingEnvironment, ApplicationDbContext context)
        {
            _hostingEnvironment = hostingEnvironment;
            _context = context;
        }

        [HttpGet]
        public IActionResult Index(string fileName = "")
        {
            ViewData["ClienteID"] = new SelectList(_context.Clientes, "Id", "Nome");
            PdfFiles fileObj = new PdfFiles();
            fileObj.Name = fileName;

           
         


            return View(fileObj);
        }

        [HttpPost]
        public IActionResult Index([FromServices] IWebHostEnvironment hostingEnvironment, IFormCollection fileObj)
        {
            ViewData["ClienteID"] = new SelectList(_context.Clientes, "Id", "Nome");
            ModelState.Remove(nameof(PdfFiles.ClientePdf));
            

            
            string value = fileObj["ClientePdfID"].ToString();
            
            List<PdfFiles> selectedFiles = new List<PdfFiles>();

            foreach (var f in fileObj.Files)
            {
                string currentFileName = f.FileName;
                string fileName = "Contracto_" + DateTime.Now.ToString("dd_MM_yyyy_hh_mm");
                string filePath = Path.Combine(hostingEnvironment.WebRootPath, "pdf", fileName);

                using (FileStream fileStream = System.IO.File.Create(filePath))
                {
                    f.CopyTo(fileStream);
                    fileStream.Flush();
                }

                var newFile = new PdfFiles()
                {
                   
                    Name = currentFileName,
                    Path = fileName ,
                    ClientePdfID = int.Parse(value),
                };

                selectedFiles.Add(newFile);
                _context.PdfFiles.Add(newFile);
                _context.SaveChanges();
            }


            return Index();
        }

        public IActionResult PDFViewerNewTab(string fileName)
        {
            string path = _hostingEnvironment.WebRootPath + "\\pdf\\" + fileName;
            return File(System.IO.File.ReadAllBytes(path), "application/pdf");
        }




        public async Task<IActionResult> Details(int cliente, int nome, string TextoAPesquisar, string nomecomercial)

        {

            var applicationDbContext = _context.PdfFiles.Include(a => a.ClientePdf);


            ViewData["ClienteID"] = new SelectList(_context.Clientes, "Id", "Nome");

            if (TextoAPesquisar != null)
            {

                return View(await _context.PdfFiles.Where(c => c.ClientePdf.Nome.Contains(TextoAPesquisar)).OrderBy(c => c.Name).Include(c => c.ClientePdf).ToListAsync());
            }


            if (nomecomercial != null)
            {
                return this.View(await _context.PdfFiles.Where(c => c.ClientePdf.Nome.Equals(nomecomercial)).Include(a => a.ClientePdf).ToListAsync());
            }

            if (cliente == 1)
            {
                return this.View(await _context.PdfFiles.OrderBy(c => c.ClientePdf.Nome).Include(a => a.ClientePdf).ToListAsync());
            }


            if (cliente == 2)
            {

                return View(await _context.PdfFiles.OrderByDescending(c => c.ClientePdf.Nome).Include(a => a.ClientePdf).ToListAsync());
            }

            if (nome == 1)
            {
                return this.View(await _context.PdfFiles.OrderBy(c => c.Name).Include(a => a.ClientePdf).ToListAsync());
            }


            if (nome == 2)
            {

                return View(await _context.PdfFiles.OrderByDescending(c => c.Name).Include(a => a.ClientePdf).ToListAsync());
            }

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: Notas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.PdfFiles == null)
            {
                return NotFound();
            }

            var nota = await _context.PdfFiles
                .FirstOrDefaultAsync(m => m.FileId == id);
            if (nota == null)
            {
                return NotFound();
            }

            return View(nota);
        }

        // POST: Notas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.PdfFiles == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Notas'  is null.");
            }
            var nota = await _context.PdfFiles.FindAsync(id);
            if (nota != null)
            {
                _context.PdfFiles.Remove(nota);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Details));
        }
        private bool PdfFileExists(int id)
        {
            return _context.PdfFiles.Any(e => e.FileId == id);
        }

        // GET: Clientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.PdfFiles == null)
            {
                return NotFound();
            }

            var pdfFiles = await _context.PdfFiles.FindAsync(id);
            if (pdfFiles == null)
            {
                return NotFound();
            }
            ViewData["ClienteID"] = new SelectList(_context.Clientes, "Id", "Nome");
            return View(pdfFiles);
        }

        // POST: Clientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FileId,Name,Path,ClientePdfID")] PdfFiles pdfFiles)
        {
            if (id != pdfFiles.FileId)
            {
                return NotFound();
            }
            ModelState.Remove(nameof(pdfFiles.ClientePdf));
            

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(pdfFiles);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PdfFileExists(pdfFiles.FileId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Details));
            }
            ViewData["ClienteID"] = new SelectList(_context.Clientes, "Id", "Nome");
            return View(pdfFiles);
        }

    }
}

Projeto de Estágio/Clientes/Clientes/Views/Clientes/Custos.cshtml
@model IEnumerable<Clientes.Models.Cliente>

@{
    ViewData["Title"] = "Contratos de Clientes";
    Layout = "~/Views/Shared/_LayoutClientes.cshtml";
}

<h1>Contratos de Clientes</h1>

<form method="post">

    <input type="text" id="TextoAPesquisar" name="TextoAPesquisar" placeholder="Cliente">



    <input class="btn btn-sm  my-2 my-sm-0" style="background-color:royalblue; color:aliceblue" type="image" src="~/img/lupa.png" width="40" height="30" alt="Submit" />

    <input type="text" id="nr" name="nr" placeholder="Valor do contrato">



    <input class="btn btn-sm my-2 my-sm-0" style="background-color:royalblue; color:aliceblue" type="image" src="~/img/lupa.png" width="40" height="30" alt="Submit" />

    <button id="btnGroupDrop1" type="button" class="btn  btn-sm dropdown-toggle show" style="background-color:royalblue; color:aliceblue" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></button>
    <div class="dropdown-menu " aria-labelledby="btnGroupDrop1" data-popper-placement="bottom-start">
        <a asp-controller="Clientes" asp-action="Custos" asp-route-Lista="1"> ALista </a>
        <div class=""></div>
        <a asp-controller="Clientes" asp-action="Custos" asp-route-Lista="2" style="  background-color:royalblue; color:aliceblue"> AListaDigital </a>
        <div class=""></div>
        <a asp-controller="Clientes" asp-action="Custos" asp-route-Lista="3" style="  background-color:royalblue; color:aliceblue"> Ambos </a>
    </div>


 
</form>



<table class="table table-hover"> 
    <thead>
        <tr class="table" style="background-color:royalblue; color:aliceblue">

            <th scope="row">
                <img src="~/img/id-card.png" width="40" height="20" />Cliente
                <a asp-action="Custos" asp-route-Nome="1" class="btn btn-sm" style="background-color:aliceblue; color:royalblue"> ↑ </a>

                <a asp-action="Custos" asp-route-Nome="2" class="btn btn-sm" style="background-color:aliceblue; color:royalblue"> ↓ </a>

            </th>
            <th scope="row">

                <img src="~/img/save-money.png" width="40" height="20" />Valor do Contrato
                <a asp-action="Custos" asp-route-Custo="1" class="btn btn-sm" style="background-color:aliceblue; color:royalblue"> ↑ </a>

                <a asp-action="Custos" asp-route-Custo="2" class="btn btn-sm" style="background-color:aliceblue; color:royalblue"> ↓ </a>

            </th>
            <th scope="row">

                <img src="~/img/agenda.png" width="40" height="20" />Data de Adesão
                <a asp-action="Custos" asp-route-Adesao="1" class="btn btn-sm" style="background-color:aliceblue; color:royalblue"> ↑ </a>

                <a asp-action="Custos" asp-route-Adesao="2" class="btn btn-sm" style="background-color:aliceblue; color:royalblue"> ↓ </a>
            </th>
            <th scope="row">

                <img src="~/img/agenda.png" width="40" height="18" />Data de Fim
                <a asp-action="Custos" asp-route-Fim="1" class="btn btn-sm" style="background-color:aliceblue; color:royalblue"> ↑ </a>

                <a asp-action="Custos" asp-route-Fim="2" class="btn btn-sm" style="background-color:aliceblue; color:royalblue"> ↓ </a>
            </th>
            <th></th>
            
            
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr class="table" style="background-color:aliceblue; color:royalblue">
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Custo) €
                </td>
                
                    @if (item.DataAdesao == null)
                    {
                    <td>
                        -----------------
                    </td>

                    }
                    else
                    {
                    <td>
                            @Html.DisplayFor(modelItem => item.DataAdesao.Value.Day)/@Html.DisplayFor(modelItem => item.DataAdesao.Value.Month)/@Html.DisplayFor(modelItem => item.DataAdesao.Value.Year)
                    </td>
                    }
                
                
                    @if(item.DataFim == null){
                        <td>
                            -----------------
                        </td>
               
                    }
                    else {
                        <td>
                        @Html.DisplayFor(modelItem => item.DataFim.Value.Day)/@Html.DisplayFor(modelItem => item.DataFim.Value.Month)/@Html.DisplayFor(modelItem => item.DataFim.Value.Year)
                        </td>
                    }
                
                <td>

                    <a asp-controller="PdfFiles" asp-action="Details" asp-route-TextoAPesquisar="@item.Nome" class="btn btn-sm btn my-2 my-sm-0" style="background-color:royalblue; color:aliceblue"> <img src="~/img/contract_white.png" width="30px" height="30px"></a>

                </td>

            </tr>             
        }
    </tbody>
</table>



<style>

    form {
        padding-top: 15px;
        padding-bottom: 25px;
    }

    h1 {
        padding-top: 10px;
        padding-bottom: 5px;
        font-family: 'Playfair Display';
    }

    tr {
        border: 1px solid;
        width: 50%;
        padding-top: 5px;
        padding-bottom: 5px;
    }
</style>

Projeto de Estágio/Clientes/Clientes/Views/Clientes/ListaClientes.cshtml
@model IEnumerable<Clientes.Models.Cliente>

@{
    ViewData["Title"] = "Lista Clientes";
    Layout = "~/Views/Shared/_LayoutClientes.cshtml";
}



<h1 class="pb-2 border-bottom">
    <span class="badge rounded-pill" style="background-color:royalblue; color:aliceblue">Clientes</span>
   
    <a asp-action="Create" class="btn btn-sm" style="color:royalblue; background-color:white"> Novo Cliente </a>
   
</h1>



    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.1.0/css/all.css" integrity="sha384-lKuwvrZot6UHsBSfcMvOkWwlCMgc0TaWr+30HWe3a4ltaBwTZhyTEggF5tJv8tbt" crossorigin="anonymous">
    <div class="container">
        <br />
        <div class="row justify-content-center">
            <div class="col-6 col-md-5 col-lg-4">
                <form class="card card-sm">
                    <div class="card-body row no-gutters align-items-center">
                        <div class="col-auto">
                            <i class="fas fa-search h4 text-body"></i>
                        </div>
                        <div class="col">
                            <input class="form-control form-control-lg form-control-borderless" type="text" id="TextoAPesquisar" name="TextoAPesquisar" placeholder="Nome / Localidade">
                        </div>
                        <div class="col-auto">
                            <button class="btn btn-lg" type="submit" style="background-color:royalblue; color:aliceblue">Search</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>


<a asp-action="ListaClientes" type="button" class="btn btn-sm" style="background-color:royalblue; color:white">Todos</a>
                                                                          
<a asp-action="Index" type="button" class="btn btn-sm" style="background-color:royalblue; color:white">  ⇆ </a>
<button id="btnGroupDrop1" type="button" class="btn  btn-sm dropdown-toggle show" style="background-color:royalblue; color:aliceblue" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="true"></button>
<div class="dropdown-menu " aria-labelledby="btnGroupDrop1"  data-popper-placement="bottom-start">
    <a asp-controller="Clientes" asp-action="ListaClientes" asp-route-Lista="1" class="btn btn-sm px-4 gap-3" style="margin:3px;  background-color:royalblue; color:aliceblue"> ALista </a>
    <a asp-controller="Clientes" asp-action="ListaClientes" asp-route-Lista="2" class="btn btn-sm px-4 gap-3" style="margin:3px;  background-color:royalblue; color:aliceblue"> AListaDigital </a>
    <a asp-controller="Clientes" asp-action="ListaClientes" asp-route-Lista="3" class="btn btn-sm px-4 gap-3" style="margin:3px;  background-color:royalblue; color:aliceblue"> Ambos </a>
</div>


<div  style="margin:20px">   

     @foreach (var item in Model)
    {
    <div class="col-20 col-md-6 col-lg-11" style="align-content:center; background-color:whitesmoke">
        <div class="card border-0 bg-light rounded shadow m-0 h-100">
            <div class="card-body p-4">
                    <span class="badge rounded-pill float-md-end mb-3 mb-sm-0" style="background-color:royalblue; color:aliceblue">@Html.DisplayFor(model => item.Tags)</span>
                <h5>@Html.DisplayFor(model => item.Nome)</h5>
                <div class="mt-3">
                        <span class="text-muted d-block"><i  aria-hidden="true"></i> <img src="~/img/id-card.png" width="40" height="20" /> @Html.DisplayFor(model => item.Representante)</span>
                        <span class="text-muted d-block"><i  aria-hidden="true"></i> <img src="~/img/local.png" width="40" height="20" /> @Html.DisplayFor(model => item.Localidade)</span>
                        <span class="text-muted d-block"><i  aria-hidden="true"></i>  <img src="~/img/location.png" width="40" height="20" /> @Html.DisplayFor(model => item.Morada)</span>
                    
                </div>

                    <div class="btn-group">
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm" style="background-color:royalblue; color:aliceblue"> Detalhes </a>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm" style="background-color:aliceblue; color:royalblue"> Editar </a>
                        <a asp-controller="PdfFiles" asp-action="Details" asp-route-id="@item.Id" asp-route-nomecomercial="@item.Nome" class="btn btn-sm" style="background-color:royalblue; color:aliceblue"> Contrato </a>
                       
                    </div>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger"> X </a>
            </div>
        </div>
    </div> 
    }
</div>

<style>
    form {
        padding-top: 15px;
        padding-bottom: 25px;
    }

    h1 {
        padding-top: 10px;
        padding-bottom: 5px;
        font-family: 'Playfair Display';
    }

    tr {
        border: 1px solid;
        width: 50%;
        padding-top: 5px;
        padding-bottom: 5px;
    }


    .button-wrap {
        padding: 15px 46px;
        color: #fff;
        background-color: #4169e1;
        /*border: 1px solid transparent;*/
        box-shadow: 0 3px 3px 0 rgba(1,1,1,.55);
        -webkit-transition: .5s cubic-bezier(.22,.61,.36,1);
        -moz-transition: .5s cubic-bezier(.22,.61,.36,1);
        transition: .5s cubic-bezier(.22,.61,.36,1);
        position: relative;
        display: inline-block;
        margin: 10px auto;
        text-transform: uppercase;
        font-size: 15px;
    }

        .button-wrap:hover {
            -webkit-filter: drop-shadow(3px 3px 20px rgba(65, 105, 225, .7));
            filter: drop-shadow(3px 3px 20px rgba(65, 105, 225, .7));
            color: #fff;
            text-decoration: none;
        }

        .button-wrap:before {
            content: "";
            position: absolute;
            top: 0px;
            left: -15px;
            width: 0;
            height: 0;
            border-top: 55px solid #4169e1;
            border-left: 15px solid transparent;
            -webkit-transition: border-color .2s ease-in-out;
            -moz-transition: border-color .2s ease-in-out;
            transition: border-color .2s ease-in-out;
        }

        .button-wrap:after {
            content: "";
            position: absolute;
            top: 0px;
            right: -15px;
            width: 0;
            height: 0;
            border-top: 55px solid #4169e1;
            border-right: 15px solid transparent;
            -webkit-transition: border-color .2s ease-in-out;
            -moz-transition: border-color .2s ease-in-out;
            transition: border-color .2s ease-in-out;
        }

    body {
        /* Safari 4-5, Chrome 1-9 */
        background: -webkit-gradient(radial, center center, 0, center center, 460, from(#ffff66), to(#2F2727));
        /* Safari 5.1+, Chrome 10+ */
        background: -webkit-radial-gradient(circle, #6581DE, white);
        /* Firefox 3.6+ */
        background: -moz-radial-gradient(circle, #ffff66, white);
        /* IE 10 */
        background: -ms-radial-gradient(circle, #ffff66, white);
        height: 600px;
    }

    .centered-form {
        margin-top: 60px;
    }

        .centered-form .panel {
            background: rgba(255, 255, 255, 0.8);
            box-shadow: rgba(0, 0, 0, 0.3) 20px 20px 20px;
        }
    
</style>